name: Alternate-NickFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.0
description: Plugin for the Nick Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [ItsTeeqo]
